// <auto-generated />
using System;
using DepartmentModule.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DepartmentModule.Migrations
{
    [DbContext(typeof(DepartmentModuleContext))]
    partial class DepartmentModuleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DepartmentModule.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectId1")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("SubjectId1");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("DepartmentModule.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int?>("ThemesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.HasIndex("ThemesId");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("DepartmentModule.Models.Book", b =>
                {
                    b.HasOne("DepartmentModule.Models.Subject", null)
                        .WithMany("AdditionalLiteratures")
                        .HasForeignKey("SubjectId");

                    b.HasOne("DepartmentModule.Models.Subject", null)
                        .WithMany("Literatures")
                        .HasForeignKey("SubjectId1");
                });

            modelBuilder.Entity("DepartmentModule.Models.Subject", b =>
                {
                    b.HasOne("DepartmentModule.Models.Book", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId");

                    b.HasOne("DepartmentModule.Models.Book", "Themes")
                        .WithMany()
                        .HasForeignKey("ThemesId");
                });
#pragma warning restore 612, 618
        }
    }
}
